# params.yaml
train:
  epochs: 250
  lr: 0.001

data:
  version: v2
  test_size: 0.3
  random_state: 42
  feature: "TV"
  target: "Sales"

predict:
  values: [199, 299]     
  model_path: null            