# params.yaml
train:
  epochs: 250
  lr: 0.001

data:
  version: v1
  test_size: 0.2
  random_state: 42
  feature: "TV"
  target: "Sales"

predict:
  values: [100, 200, 300]     
  model_path: null            