# params.yaml
train:
  epochs: 200
  lr: 0.001

data:
  version: v3
  test_size: 0.2
  random_state: 42
  feature: "Radio"
  target: "Sales"

predict:
  values: [25, 50, 10]     
  model_path: null            